from sky import Sky
s = Sky()
s.init_star_r(0.02)
s.read_frame()
s.read_line()
s.read_hip()
s.init_area(s.fs[0], s.fs[1], s.fs[2], s.fs[3], s.fs[4], s.fs[5], s.fs[6], s.fs[7], 6, 400)
s.draw_alpha_lines()
s.draw_delta_lines()
s.draw_alpha_text()
s.draw_delta_text()
s.draw_constellation_lines()
s.draw_star_hip()
s.draw_legend()
for v in s.f1.values():
    if v[0] == 1:s.draw_frame_link(1, v[1], v[3], v[4], v[6])
s.draw_frame(True, False, False, False)
s.save_img()
s.init_area(s.fn[0], s.fn[1], s.fn[2], s.fn[3], s.fn[4], s.fn[5], s.fn[6], s.fn[7], 6, 400)
s.draw_alpha_lines()
s.draw_delta_lines()
s.draw_alpha_text()
s.draw_delta_text()
s.draw_constellation_lines()
s.draw_star_hip()
s.draw_legend()
for v in s.f1.values():
    if v[0] == 2:s.draw_frame_link(2, v[1], v[3], v[4], v[6])
s.draw_frame(False, False, True, False)
s.save_img()
for k, v in s.f1.items():
    s.init_area(v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7], 9, 400)
    s.draw_alpha_lines()
    s.draw_delta_lines()
    s.draw_alpha_text()
    s.draw_delta_text()
    s.draw_constellation_lines()
    s.draw_star_hip()
    s.draw_legend()
    for w in s.f2.values():
        if w[0] == k:s.draw_frame_link(k, w[1], w[3], w[4], w[6])
    s.draw_frame(True, True, True, True)
    s.save_img()
for k, v in s.f2.items():
    s.init_area(v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7], 16, 400)
    s.draw_alpha_lines(5)
    s.draw_delta_lines(1)
    s.draw_alpha_text(5)
    s.draw_delta_text(1)
    s.draw_constellation_lines()
    s.draw_star_hip()
    s.draw_legend()
    s.draw_frame(True, True, True, True)
    s.save_img()