import sky
s = sky.sky(0, 0, 360, 0, 90, 90, 6, 0.9, 15000)
s.draw_alpha_lines()
s.draw_delta_lines()
s.draw_frame(False, False, True, False)
s.draw_constellation_lines()
s.draw_star_hip()
s.draw_legend()
s.save_img(1200, 'n')
s = sky.sky(0, 180, 360, -90, -90, 0, 6, 0.9, 15000)
s.draw_alpha_lines()
s.draw_delta_lines()
s.draw_frame(True, False, False, False)
s.draw_constellation_lines()
s.draw_star_hip()
s.draw_legend()
s.save_img(1200, 's')